export default {
    hair: {
        true: [
            {id: 1, name: 'Short', price: 1000, creator: false},
            {id: 2, name: 'Hawk', price: 1000, creator: true},
            {id: 3, name: 'Hipster', price: 1000, creator: true},
            {id: 4, name: 'Side Bang', price: 1000, creator: false}, 
            {id: 5, name: 'Short Cut', price: 1000, creator: false},
            {id: 6, name: 'Biker', price: 1000, creator: true},
            {id: 7, name: 'Ponytail', price: 1000, creator: false},
            {id: 8, name: 'Braids', price: 1000, creator: true},
            {id: 9, name: 'Slick', price: 1000, creator: false},
            {id: 10, name: 'Short Style', price: 1000, creator: true},
            {id: 11, name: 'Spikes', price: 1000, creator: true},
            {id: 12, name: 'Caesar', price: 1000, creator: false},
            {id: 13, name: 'Choppy', price: 1000, creator: true},
            {id: 14, name: 'Dreads', price: 1000, creator: true},
            {id: 15, name: 'Long Hair', price: 1000, creator: false},
            {id: 16, name: 'Messy Curls', price: 1000, creator: false}, 
            {id: 17, name: 'Surfer', price: 1000, creator: false},
            {id: 18, name: 'Side Part', price: 1000, creator: true},
            {id: 19, name: 'Slick Back', price: 1000, creator: false},
            {id: 20, name: 'Long', price: 1000, creator: false},
            {id: 21, name: 'Young Hipster', price: 1000, creator: true},
            {id: 22, name: 'Bushy', price: 1000, creator: true},
            {id: 24, name: 'Classic Braids', price: 1000, creator: false},
            {id: 25, name: 'Palm Braids', price: 1000, creator: false},
            {id: 26, name: 'Lightning Braids', price: 1000, creator: false},
            {id: 27, name: 'Top Braids', price: 1000, creator: false}, 
            {id: 28, name: 'Zigzag Braids', price: 1000, creator: false},
            {id: 29, name: 'Snail Braids', price: 1000, creator: false},
            {id: 30, name: 'High Top', price: 1000, creator: false},
            {id: 31, name: 'Messy Back Sweep', price: 1000, creator: false},
            {id: 32, name: 'Trimmed Back Sweep', shortname: "Trim Back", price: 1000, creator: true},
            {id: 33, name: 'Trimmed Side Sweep', shortname: "Trim Side", price: 1000, creator: true},
            {id: 34, name: 'Spiky Mohawk', price: 1000, creator: false},
            {id: 35, name: 'Styler', price: 1000, creator: true},
            {id: 36, name: 'Layered Styler', price: 1000, creator: false},
        ],
        false: [
            {id: 1, name: 'Short', price: 1000, creator: true},
            {id: 2, name: 'Layers', price: 1000, creator: true},
            {id: 3, name: 'Braids', price: 1000, creator: true},
            {id: 4, name: 'Tail', price: 1000, creator: true},
            {id: 5, name: 'Mohawk', price: 1000, creator: true},
            {id: 6, name: 'Braids', price: 1000, creator: false},
            {id: 7, name: 'Bob', price: 1000, creator: false},
            {id: 8, name: 'Hawk', price: 1000, creator: false},
            {id: 9, name: 'Shell', price: 1000, creator: false},
            {id: 10, name: 'Long Bob', price: 1000, creator: true},
            {id: 11, name: 'Free', price: 1000, creator: true},
            {id: 12, name: 'Pixel', price: 1000, creator: true},
            {id: 13, name: 'Shaved Temples', price: 1000, creator: true},
            {id: 14, name: 'Knot', price: 1000, creator: false},
            {id: 15, name: 'Wavy Bob', price: 1000, creator: true},
            {id: 16, name: 'Beauty', price: 1000, creator: true},
            {id: 17, name: 'Bun', price: 1000, creator: true},
            {id: 18, name: 'Flapper Bob', price: 1000, creator: false},
            {id: 19, name: 'Tight Knot', price: 1000, creator: false},
            {id: 20, name: 'Dandelion', price: 1000, creator: true},
            {id: 21, name: 'Explosion', price: 1000, creator: false},
            {id: 22, name: 'Top Knot', price: 1000, creator: false},
            {id: 25, name: 'Broken Braids', price: 1000, creator: false},
            {id: 26, name: 'Leaf Braids', price: 1000, creator: false},
            {id: 27, name: 'Zigzag Braids', price: 1000, creator: false},
            {id: 28, name: 'Pigtails w/ Bangs', price: 1000, creator: false},
            {id: 29, name: 'Wave Braids', price: 1000, creator: false},
            {id: 30, name: 'Curl Braids', price: 1000, creator: false},
            {id: 31, name: 'Roll Bangs', price: 1000, creator: false},
            {id: 32, name: 'Messy Back Sweep', price: 1000, creator: false},
            {id: 33, name: 'Trimmed Back Sweep', price: 1000, creator: true},
            {id: 34, name: 'Trimmed Side Sweep', price: 1000, creator: true},
            {id: 35, name: 'Spiky Mohawk', price: 1000, creator: false},
            {id: 36, name: 'Bandana & Braids', price: 1000, creator: false},
            {id: 37, name: 'Chelsea', price: 1000, creator: true},
            {id: 38, name: 'Layered Styler', price: 1000, creator: true},
        ]
    },

    eyebrows: [
        {id: 0, name: 'Neat', price: 100, creator: true},
        {id: 1, name: 'Trendy', price: 100, creator: true},
        {id: 2, name: 'Cleopatra', price: 100, creator: false},
        {id: 3, name: 'Ironic', price: 100, creator: true},
        {id: 4, name: 'Feminine', price: 100, creator: false},
        {id: 5, name: 'Seductive', price: 100, creator: false}, 
        {id: 6, name: 'Frowned', price: 100, creator: true},
        {id: 7, name: 'Chick', price: 100, creator: false},
        {id: 8, name: 'Triumphant', price: 100, creator: false},
        {id: 9, name: 'Carefree', price: 100, creator: true},
        {id: 10, name: 'Arc', price: 100, creator: true},
        {id: 11, name: 'Mouse', price: 100, creator: true},
        {id: 12, name: 'Double Cut', price: 100, creator: false},
        {id: 13, name: 'Hollow', price: 100, creator: false},
        {id: 14, name: 'Pencil Drawn', price: 100, creator: false},
        {id: 15, name: 'Plucked', price: 100, creator: false},
        {id: 16, name: 'Straight Thin', price: 100, creator: false},
        {id: 17, name: 'Natural', price: 100, creator: false},
        {id: 18, name: 'Thick', price: 100, creator: true},
        {id: 19, name: 'Untidy', price: 100, creator: true},
        {id: 20, name: 'Wide', price: 100, creator: false},
        {id: 21, name: 'Regular', price: 100, creator: false},
        {id: 22, name: 'South-European', price: 100, creator: true},
        {id: 23, name: 'Well-groomed', price: 100, creator: true}, 
        {id: 24, name: 'Bushy', price: 100, creator: true},
        {id: 25, name: 'Feathered', price: 100, creator: true},
        {id: 26, name: 'Spiky', price: 100, creator: false},
        {id: 27, name: 'Unibrow', price: 100, creator: false},
        {id: 28, name: 'Winged', price: 100, creator: false},
        {id: 29, name: 'Triple Cut', price: 100, creator: true},
        {id: 30, name: 'Arc Cut', price: 100, creator: false},
        {id: 31, name: 'Trimmed', price: 100, creator: false},
        {id: 32, name: 'Fading', price: 100, creator: false}, 
        {id: 33, name: 'Cut', price: 100, creator: false},
    ],

    facialhair: [
        {id: 255, name: "Clean Shaven", price: 100, creator: true},
        {id: 0, name: 'Light Stubble', price: 100, creator: true},
        {id: 1, name: 'Balbo', price: 100, creator: true},
        {id: 2, name: 'Round Beard', price: 100, creator: true},
        {id: 3, name: 'Goatee', price: 100, creator: true},
        {id: 4, name: 'Goatee Small', price: 100, creator: true},
        {id: 5, name: 'Patch', price: 100, creator: true},
        {id: 6, name: 'Thin Beard', price: 100, creator: true},
        {id: 7, name: 'Short Beard', price: 100, creator: true},
        {id: 8, name: 'Musketeer', price: 100, creator: true},
        {id: 9, name: 'Mustache', price: 100, creator: true},
        {id: 10, name: 'Trimmed Beard', price: 100, creator: true},
        {id: 11, name: 'Stubble', price: 100, creator: true},
        {id: 12, name: 'Round Beard 2', price: 100, creator: true},
        {id: 13 , name: 'Horseshoe Beard', price: 100, creator: false},
        {id: 14, name: 'Pencil Mustache + Sides', price: 100, creator: false},
        {id: 15, name: 'Belt Beard', price: 100, creator: false},
        {id: 16, name: 'Balbo & Sideburns', price: 100, creator: false},
        {id: 17, name: 'Sideburns', price: 100, creator: false},
        {id: 18, name: 'Short Beard Alt', price: 100, creator: false},
        {id: 19, name: 'Dali', price: 100, creator: false},
        {id: 20, name: 'Dali + Beard', price: 100, creator: false},
        {id: 21, name: 'Handlebar', price: 100, creator: false},
        {id: 22, name: 'Patch + Mustache', price: 100, creator: false},
        {id: 23, name: 'English Mustache + Chin', price: 100, creator: false},
        {id: 24, name: 'Hollywood Beard', price: 100, creator: false},
        {id: 25, name: 'Fu Manchu', price: 100, creator: false},
        {id: 26, name: 'Patch + Sideburns', price: 100, creator: false},
        {id: 27, name: 'Wide Sideburns', price: 100, creator: false},
        {id: 28, name: 'Curtain Beard', price: 100, creator: false},
    ],

    chesthair: [
        {id: 255, name: "Smooth", price: 100},
        {id: 0, name: "Natural", price: 100},
        {id: 1, name: "Strip", price: 100},
        {id: 2, name: "Tree", price: 100},
        {id: 3, name: "Hairy", price: 100}, 
        {id: 4, name: "Overgrown", price: 100},
        {id: 5, name: "Monkey", price: 100},
        {id: 6, name: "Combed Monkey", price: 100},
        {id: 7, name: "Bikini", price: 100},
        {id: 8, name: "Lightning", price: 100},
        {id: 9, name: "Reverse Lightning", price: 100},
        {id: 10, name: "Heart", price: 100},
        {id: 11, name: "Mustache", price: 100},
        {id: 12, name: "Smiley", price: 100}, 
        {id: 13, name: "Skull", price: 100},
        {id: 14, name: "Path", price: 100},
        {id: 15, name: "Path + Nipples", price: 100}, 
        {id: 16, name: "Hairy Arms", price: 100}
    ],

    blemishes: [
        {id: 255, name: "None"},
        {id: 0, name: "Rubella"},
        {id: 1, name: "Measles"},
        {id: 2, name: "Spots"},
        {id: 3, name: "Rash"},
        {id: 4, name: "Acne"},
        {id: 5, name: "Coating"},
        {id: 6, name: "Pustules"},
        {id: 7, name: "Pimples"},
        {id: 8, name: "Large Pimples"},
        {id: 9, name: "Acne Alt"},
        {id: 10, name: "Cheek Rash"},
        {id: 11, name: "Face Rash"},
        {id: 12, name: "Picked"},
        {id: 13, name: "Puberty"},
        {id: 14, name: "Ulcer"},
        {id: 15, name: "Jaw Rash"},
        {id: 16, name: "Two-faced"},
        {id: 17, name: "T-Zone"},
        {id: 18, name: "Oily Skin"},
        {id: 19, name: "Scars"},
        {id: 20, name: "Acne Scars"},
        {id: 21, name: "Pimple Marks"},
        {id: 22, name: "Herpes"},
        {id: 23, name: "Lichen"},
    ],

    ageing: [
        {id: 255, name: "None"},
        {id: 0, name: "Eye Wrinkles"},
        {id: 1, name: "Signs of Aging"},
        {id: 2, name: "Middle Age"},
        {id: 3, name: "Wrinkles"},
        {id: 4, name: "Depression"},
        {id: 5, name: "Elderly"},
        {id: 6, name: "Old"},
        {id: 7, name: "Weathered Skin"},
        {id: 8, name: "Wrinkled Skin"},
        {id: 9, name: "Sagging Skin"},
        {id: 10, name: "Hard Life"},
        {id: 11, name: "Vintage"},
        {id: 12, name: "Pension Age"},
        {id: 13, name: "Addiction"},
        {id: 14, name: "Senile"},
        {id: 15, name: "Depressed"} 
    ],

    complexion: [
        {id: 255, name: "None"},
        {id: 0, name: "Blush"},
        {id: 1, name: "Stubble Irritation"},
        {id: 2, name: "Redness"},
        {id: 3, name: "Sunburn"},
        {id: 4, name: "Bruises"},
        {id: 5, name: "Alcoholic"},
        {id: 6, name: "Spots"},
        {id: 7, name: "Totem"},
        {id: 8, name: "Blood Vessels"},
        {id: 9, name: "Damage"},
        {id: 10, name: "Pale"},
        {id: 11, name: "Dead Pale"}
    ],

    molesfreckles: [
        {id: 255, name: "None"},
        {id: 0, name: "Angel"},
        {id: 1, name: "Everywhere"},
        {id: 2, name: "Patchy"},
        {id: 3, name: "Single"},
        {id: 4, name: "Nose Bridge"},
        {id: 5, name: "Doll"},
        {id: 6, name: "Fairy"},
        {id: 7, name: "Tanned"},
        {id: 8, name: "Moles"},
        {id: 9, name: "Row"},
        {id: 10, name: "Model Look"},
        {id: 11, name: "Rare"},
        {id: 12, name: "Freckles"},
        {id: 13, name: "Drops"},
        {id: 14, name: "Double"},
        {id: 15, name: "One Side"},
        {id: 16, name: "Pairs"},
        {id: 17, name: "Warts"}
    ],

    sundamage: [
        {id: 255, name: "None"},
        {id: 0, name: "Uneven"},
        {id: 1, name: "Sandpaper"},
        {id: 2, name: "Spotted"},
        {id: 3, name: "Rough"},
        {id: 4, name: "Hard"},
        {id: 5, name: "Coarse"},
        {id: 6, name: "Rugged"},
        {id: 7, name: "Uneven Alt"},
        {id: 8, name: "With Folds"},
        {id: 9, name: "Cracked"},
        {id: 10, name: "Firm"},
    ],

    eyescolor: [
        {id: 0, name: 'Green', price: 100},
        {id: 1, name: 'Emerald', price: 100},
        {id: 2, name: 'Light Blue', price: 100},
        {id: 3, name: 'Blue', price: 100},
        {id: 4, name: 'Light Brown', price: 100},
        {id: 5, name: 'Dark Brown', price: 100},
        {id: 6, name: 'Hazel', price: 100},
        {id: 7, name: 'Dark Grey', price: 100},
        {id: 8, name: 'Light Grey', price: 100}
    ],

    blush: [
        {id: 255, name: "None", price: 100},
        {id: 0, name: "Full Blush", price: 100},
        {id: 1, name: "Angled", price: 100},
        {id: 2, name: "Round", price: 100},
        {id: 3, name: "Horizontal", price: 100},
        {id: 4, name: "Cheekbones", price: 100},
        {id: 5, name: "Beauty", price: 100},
        {id: 6, name: "80s Style", price: 100},
    ],

    eyesmakeup: [
        {id: 255, name: "None", price: 100},
        {id: 0, name: "Smokey Black", price: 100},
        {id: 1, name: "Bronze", price: 100},
        {id: 2, name: "Soft Grey", price: 100},
        {id: 3, name: "Retro Glam", price: 100},
        {id: 4, name: "Natural", price: 100},
        {id: 5, name: "Cat Eyes", price: 100},
        {id: 6, name: "Chick", price: 100},
        {id: 7, name: "Vamp", price: 100},
        {id: 8, name: "Vinewood Glamour", price: 100},
        {id: 9, name: "Bubblegum", price: 100},
        {id: 10, name: "Sea Dream", price: 100},
        {id: 11, name: "Pin-Up", price: 100},
        {id: 12, name: "Purple Passion", price: 100},
        {id: 13, name: "Smokey Cat Eyes", price: 100},
        {id: 14, name: "Fire Ruby", price: 100},
        {id: 15, name: "Stage Princess", price: 100},
        {id: 16, name: "Mascara", price: 100},
        {id: 17, name: "Bloody Tears", price: 100},
        {id: 18, name: "Heavy Metal", price: 100},
        {id: 19, name: "Sadness", price: 100},
        {id: 20, name: "Prince of Darkness", price: 100},
        {id: 21, name: "Rocker", price: 100},
        {id: 22, name: "Goth", price: 100},
        {id: 23, name: "Punk", price: 100},
        {id: 24, name: "Broken", price: 100},
    ],

    lipstick: [
        {id: 255, name: "None", price: 100},
        {id: 0, name: "Colored Matte", price: 100},
        {id: 1, name: "Colored Glossy", price: 100},
        {id: 2, name: "Contour Matte", price: 100},
        {id: 3, name: "Contour Glossy", price: 100},
        {id: 4, name: "Bold Contour Matte", price: 100},
        {id: 5, name: "Bold Contour Glossy", price: 100},
        {id: 6, name: "Unpainted Matte Contour", price: 100},
        {id: 7, name: "Unpainted Gloss Contour", price: 100},
        {id: 8, name: "Smeared Lipstick", price: 100},
        {id: 9, name: "Geisha", price: 100},
    ]
        }
