export default {
    true: {
        head: [
            {name: "None", drawable: -1, texture: 0},
            {name: "Black Bucket Hat", drawable: 3, texture: 1},
            {name: "Beige Bucket Hat", drawable: 3, texture: 2},
            {name: "Black Beanie", drawable: 5, texture: 0},
            {name: "Grey Beanie", drawable: 5, texture: 1},
            {name: "Green Cap Backwards", drawable: 9, texture: 5},
            {name: "Green Cap Forward", drawable: 10, texture: 5},
            {name: "Purple Cap Forward", drawable: 10, texture: 7},
            {name: "Christmas Hat 'Tree'", drawable: 97, texture: 0},
            {name: "Christmas Hat 'Wizard'", drawable: 97, texture: 3},
            {name: "Christmas Hat 'Bells'", drawable: 97, texture: 2},
        ],
        tops: [
            {name: "White T-Shirt", drawable: 0, texture: 0},
            {name: "Grey T-Shirt", drawable: 0, texture: 1},
            {name: "Black T-Shirt", drawable: 0, texture: 2},
            {name: "Yellow T-Shirt", drawable: 0, texture: 3},
            {name: "Hoodie", drawable: 8, texture: 0},
            {name: "Christmas Sweater", drawable: 194, texture: 0},
            {name: "White Shirt", drawable: 144, texture: 0},
        ],
        legs: [
            {name: "Dark Jeans", drawable: 1, texture: 1},
            {name: "Grey Jeans", drawable: 1, texture: 2},
            {name: "Blue Jeans", drawable: 1, texture: 5},
            {name: "Dark Slim Jeans", drawable: 4, texture: 0},
            {name: "Grey Slim Jeans", drawable: 4, texture: 1},
            {name: "Light Slim Jeans", drawable: 4, texture: 2},
            {name: "Beige Shorts", drawable: 15, texture: 0},
            {name: "Brown Shorts", drawable: 15, texture: 1},
            {name: "White Shorts", drawable: 15, texture: 2},
            {name: "Dark Shorts", drawable: 15, texture: 3},
        ],
        shoes: [
            {name: "Black Sneakers", drawable: 1, texture: 0},
            {name: "White Sneakers", drawable: 1, texture: 1},
            {name: "Red Sneakers", drawable: 1, texture: 10},
            {name: "Brown Boots", drawable: 12, texture: 0},
            {name: "Light Blue Boots", drawable: 12, texture: 2},
            {name: "Black Boots", drawable: 12, texture: 6},
        ]
    },
    false: {
        head: [
            {name: "None", drawable: -1, texture: 0},
            {name: "Black Beanie", drawable: 5, texture: 0},
            {name: "White Beanie", drawable: 5, texture: 1},
            {name: "Pink Beanie", drawable: 5, texture: 2},
            {name: "Dark Bucket Hat", drawable: 3, texture: 7},
            {name: "Beige Cap", drawable: 10, texture: 7},
            {name: "Christmas Hat", drawable: 97, texture: 0},
            {name: "Christmas Hat 'Tree'", drawable: 39, texture: 0},
        ],
        tops: [
            {name: "White Tank Top", drawable: 0, texture: 0},
            {name: "Pink Tank Top", drawable: 0, texture: 1},
            {name: "Black Tank Top", drawable: 0, texture: 2},
            {name: "Blue Tank Top", drawable: 0, texture: 6},
            {name: "White Polo", drawable: 14, texture: 0},
            {name: "Pink Polo", drawable: 14, texture: 1},
            {name: "Light Pink Polo", drawable: 14, texture: 2},
            {name: "Black Polo", drawable: 14, texture: 3},
            {name: "Christmas T-Shirt", drawable: 19, texture: 0},
        ],
        legs: [
            {name: "Light Jeans", drawable: 0, texture: 0},
            {name: "Dark Jeans", drawable: 0, texture: 1},
            {name: "Short White Shorts", drawable: 10, texture: 0},
            {name: "Short Blue Shorts", drawable: 10, texture: 1},
            {name: "White Sweatpants", drawable: 2, texture: 0},
            {name: "Grey Sweatpants", drawable: 2, texture: 1},
            {name: "Black Sweatpants", drawable: 2, texture: 2},
        ],
        shoes: [
            {name: "White Sneakers", drawable: 1, texture: 0},
            {name: "Dark Sneakers", drawable: 1, texture: 1},
            {name: "Grey Sneakers", drawable: 1, texture: 2},
            {name: "Dark Dress Shoes", drawable: 13, texture: 0},
        ]
    }
}
